import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import BackgroundImage from "@/components/background/BackgroundImage";
import RootLayoutProvider from "@/providers/RootLayoutProvider";
import "@aptos-labs/wallet-adapter-ant-design/dist/index.css";
import "./globals.css";
import TopBar from "@/components/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wgmi Exchange",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleAnalytics gaId="G-*******" />
        <BackgroundImage />
        <RootLayoutProvider>
          <TopBar />
          {children}
        </RootLayoutProvider>
      </body>
    </html>
  );
}
